site_name: Mewgenics Modding Documentation
site_url: https://mewgenicsmoddingdocs

nav:
  - Home: index.md
  - Docs:
    - Home: index.md
    - "Getting Started": _index_gettingstarted.md
    - "Commands": _index_commands.md
    - "GON Overview": GONOverview.md
    - "SWF Overview": SWFOverview.md
  - GON:
    - Home: GON_home.md
    - "Enums":
        - "Abilities":
          - "AOE Restrictions": GON_enums_abilities_aoe_restrictions.md
          - "Cost": GON_enums_abilities_cost.md
          - "Item Slots": GON_enums_abilities_itemslots.md
          - "Restrictions": GON_enums_abilities_restrictions_cost.md
          - "Sounds": GON_enums_abilities_sounds.md
        - "Meta": 
          - "Elements": GON_enums_meta_elements.md
          - "Stats": GON_enums_meta_stats.md
        - "Shared":
          - "Damage": GON_enums_shared_damage.md
          - "Graphics": GON_enums_shared_graphics.md
          - "Meta": GON_enums_shared_meta.md
          - "Spawn": GON_enums_shared_spawn.md
          - "Target": GON_enums_shared_target.md
    - "Abilities": GON_ABI_abilitieshome.md
    - "Ability Templates": GON_ABI_abilitytemplates.md
  - SWF:
    - Home: SWF_home.md
    - "Appendation": SWF_appendation.md
  - Tools:
    - Home: TOOLS_home.md
    - "Templates": 
      - "Mod Templates": TOOLS_modtemplates.md
  - DLL:
    - Home: DLL_home.md
    - "Custom Status Effects": DLL_customstatuses.md
    - "Status Effect Pipeline": DLL_statuspipeline.md

theme:
    name: material
    custom_dir: overrides
    features:
        - search.suggest
        - search.highlight
        - search.share
        - navigation.tabs
        - navigation.instant
        - navigation.top
    icon:
        repo: fontawesome/brands/github
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: deep orange
          accent: deep orange
          toggle:
            icon: material/weather-night
            name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: deep orange
          accent: deep orange
          toggle:
            icon: material/weather-sunny
            name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      url_download: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
plugins:
  - search:
      separator: '[\s\-\.\_\·]+'
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
  - tags:
      tags_file: tags.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CVS-otherwise-Callie/mewgenics-modding-documents
      name: "Mewgenics Modding Wiki on Github"
  version:
    provider: mike
    default: rep
  analytics:
    provider: google
    property: G-ZBKP3LLT96
extra_css:
    - css/custom.css
extra_javascript:
    - https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
    - js/tablesort.number.min.js
    - js/customJS.js
    - js/jquery.mark.min.js
copyright: "Copyright &copy; 2026 CVS-Otherwise-Callie (Discord: ia_svc)"
repo_url: https://github.com/CVS-otherwise-Callie/mewgenics-modding-documents
repo_name: CVS-otherwise-Callie/mewgenics-modding-documents
edit_uri: edit/main/docs/
use_directory_urls: False