site_name: Mewgenics Modding Documentation
site_url: https://mewgenicsmoddingdocs

nav:
  - Home: index.md
  - Docs:
    - Home: index.md
    - "SWF Modding":
      - "SWF Overveiw": SWFOverview.md
      - "Tutorials": swf/SWFTutorials.md
    - "Gon Modding":
      - "Gon Overview": GONOverview.md
      - "Tutorials": gon/GONTutorials.md
  - SWF:
    - Home: swf/home.md
    - "Setup": swf/importandexporttutorial.md
    - "Appendation": swf/appendation.md
    - "Properties": swf/properties.md
  - GON:
    - Home: gon/home.md
    - "Enums":
      - "Ability (Meta) Enums": gon/enums/abi_metaabilities.md
      - "Ability (Graphics) Enums": gon/enums/abi_graphicabilities.md
      - "Ability (Sounds) Enums": gon/enums/abi_soundabilities.md
      - "Ability (Cost) Enums": gon/enums/abi_costabilities.md
      - "Ability (Target) Enums": gon/enums/abi_targetabilities.md
      - "Ability (Damage) Enums": gon/enums/abi_damageabilities.md
      - "Ability (Spawn) Enums": gon/enums/abi_spawnabilities.md
      - "Elements": gon/enums/elements.md
    - "Abilities":
      - "Abilities": gon/abi_abilitieshome.md
      - "Boss Abilities": gon/abi_bosscatabilities.md
      - "Cat Abilities": gon/abi_catabilities.md
      - "Enemy Abilities": gon/abi_enemyabilities.md

theme:
    name: material
    custom_dir: overrides
    features:
        - search.suggest
        - search.highlight
        - search.share
        - navigation.tabs
        - navigation.instant
        - navigation.top
    icon:
        repo: fontawesome/brands/github
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: deep orange
          accent: deep orange
          toggle:
            icon: material/weather-night
            name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: deep orange
          accent: deep orange
          toggle:
            icon: material/weather-sunny
            name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      url_download: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
plugins:
  - search:
      separator: '[\s\-\.\_\·]+'
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
  - tags:
      tags_file: tags.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CVS-otherwise-Callie/mewgenics-modding-documents
      name: "Mewgenics Modding Wiki on Github"
  version:
    provider: mike
    default: rep
  analytics:
    provider: google
    property: G-ZBKP3LLT96
extra_css:
    - css/custom.css
extra_javascript:
    - https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
    - js/tablesort.number.min.js
    - js/customJS.js
    - js/jquery.mark.min.js
copyright: "Copyright &copy; 2026 CVS-Otherwise-Callie (Discord: ia_svc)"
repo_url: https://github.com/CVS-otherwise-Callie/mewgenics-modding-documents
repo_name: CVS-otherwise-Callie/mewgenics-modding-documents
edit_uri: edit/main/docs/
use_directory_urls: False